# -*- coding: utf-8 -*-
"""파이썬_연습.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X0SWYvDLkuUZ93SVlbHoIPqE3yVVhg_N
"""

# 기본 사용법

# CTRL + MA (above)
# CTRL + MB (below)
# CTRL + MD (delete)
# CTRL + ENTER (실행)
# CTRL + / 
# Indentation 주의

"""#1장"""

33+55

7*5/2

9 * (5 - 7) /3

print("3 + 5 = ", 8)

print(1,2,3,"Hello", "World")

print("3 + 5 = ", 3 + 5)

# 메모리 공간에 30을 저장하고, 그 공간에다 val이라는 이름을 붙임
# 30(오른쪽)을 val(왼쪽)에 대입(할당)

val = 30

x = 3 * 50
y = x + 120
z = y /3
print(z)

v1 = 25
v2 = 30
print(v1 + v2)

# 이름표 이동
# 오른쪽을 왼쪽에 대입

x = 100
print(x)
x = 3.14
print(x)
x = "Hi~"
print(x)

x = 3 * 50 
x = x + 120
x = x / 3
print(x)



# 연습문제 01-1
# 문제1 : 자신의 이름 출력
# 문제2 : 1-10까지의 합

print("진대용")
print("1+2+3+4+5+6+7+8+9+10",1+2+3+4+5+6+7+8+9+10)

x,y = 121, 797
print(x,y)

x = y
print(x,y)

x, y = 121, 797
x, y = y, x
print(x,y)

"""#2장 함수"""

# 함수

def great():
  print("반갑습니다")
  print("파이썬 세계로 오신걸 환영합니다.")

great()
great()
great()

def great2(name):
  print("반갑습니다",name)
  print(name, "님은 파이썬의 세계로 오셨습니다")
  
great2("John")
great2("Yoon")

def adder(n1,n2):
  print("n1 + n2 = ",n1+n2)
  
adder(10,20)

# 연습문제 2-2

# 문제1 : 매개변수를 통해 문자열을 전달받아 3번 출력

def print_str(x):
  print(x)
  print(x)
  print(x)
  
print_str("안녕?")

def adder(n1,n2):
  sum = n1 + n2
  return sum

result = adder(10,20)
print(result)

# 연습문제 2-3

# 문제2 : 두개의 숫자를 받아 평균계산

def mean(n1,n2):
  m = (n1 + n2) / 2
  return m

result = mean(10,20)
print(result)

# 참고 : 주석 (CTRL + /)

# 2-4 - 7 실습생략

# 2-8 main함수가 있는 방식으로 예제 작성

def adder(num1,num2):
  return num1 + num2
def minus(num1,num2):
  return num1 - num2
def mul(num1,num2):
  return num1 * num2
def div(num1,num2):
  return num1 * num2

def main():
  print(adder(5,3))
  print(minus(5,3))
  print(mul(5,3))
  print(div(5,3))
  
main()

"""#3장"""

str = input("몇살이세요? : ")
print(str)

num = "31" + "24"
print(num)

# 문제 3-1 : 2개의 입력을 받아 합치기

def concat(s1,s2):
  return s1 + s2

print(concat("안녕","하세요"))
print(concat("12","34"))

year = input("This year: ")
# year = eval(input("This year: "))
# year = int(input("This year: ")) # int : 정수형, float : 소수형

print(year+1)

# 0~3 까지 출력

for i in [0,1,2,3]:
  print(i)

# 1에서 10까지 더하기

sum = 0
for i in [0,1,2,3,4,5,6,7,8,9,10]:
  sum = sum + i
print(sum)

# 연습문제 3-3 : 구구단 7단을 모두 출력

for i in [1,2,3,4,5,6,7,8,9]:
  #print(i*7)
  print(i,"* 7 =",i*7)

list(range(1,10))

for i in range(1,10):
  #print(i*7)
  print(i,"* 7 =",i*7)

for i in range(10):
  #print(i*7)
  print(i,"* 7 =",i*7)

# 연습문제 3-3

# 문제 1 : 1,3,5,7,9 합 출력

sum = 0 
for i in [1,3,5,7,9]:
  sum =  sum + i
  
print(sum)

sum = 0 
for i in range(1,10,2):
  sum =  sum + i
  
print(sum)

"""# 4장"""

data1 = 1  # 정수 1을 data1에 저장
data2 = 2.4 # 실수 2.4를 data2에 저장
data3 = "안녕" #문자열 안녕을 data3에 저장

print(type(1))
print(type(2.4))
print(type(data3))


print(type(data1))
print(type(data2))
print(type(data3))

# 정수 / 정수 = 실수값

5 / 2

5 // 2

5 % 2

2 ** 4

# 타입 변환 : type casting

num = 10
num = float(num)
type(num)
print(num)

num = "10"
#num = "10안녕"
num = float(num)

num = int(input("좋아한는 숫자는 : "))
print(num)

# 복합 대입 연산자

num =10
num = num + 1
num += 1
print(num)

# 7장

True

False

3 > 10

3 < 10

r = 3 < 10
r
type(r)

num = int(input("정수 입력 : "))
if num > 0:
  print("양의정수")
elif num == 0:
  print("0")
else:
  print("음의정수")

num = int(input("정수 입력 : "))
if num == 1:
  print("1을 입력했습니다.")
elif num == 2:
  print("2를 입력했습니다.")
elif num == 3:
  print("3을 입력했습니다.")
else:
  print("1,2,3 아닌 정수 입력했습니다")

# 2의 배수이면서 3의 배수인지 확인

num = int(input("입력 :"))
if num % 2 == 0:
  if num % 3 == 0:
    print("OK")
  else:
    print("NO")
print("NO")

num = int(input("입력 :"))
if num % 2 == 0 and num % 3 == 0:
  print("OK")
else:
  print("NO")

# 연습문제

# 키보드로 부터 정수 입력받음
# 0이하 : 0보다 작습니다.
# 0-9 : 0-9사이입니다
# 10-19 : 10-19사이입니다.
# 나머지 : 20 이상입니다.

num = int(input("입력:"))
if num < 0:
  print("0이하")
elif num < 10 :
  print("1-9")
elif num < 20 :
  print("10-19")
else:
  print("20이상")



"""#5장"""

for i in [1,2,3]:
  print(i, end="\n")
  
for i in [1,2,3]:
  print(i, end=" ")

# 리스트
type([1,2,3])

l = [1,'hello world',3.3]

type(l[0])

print(l[1])

[1,2,3] + [4,5]

[1,2,3] * 2

s = [1,2,3,4,5]
s[0] = s[3]
print(s)
print(s[-1])

# 연습문제 5
# 1번째 원소와 마지막 원소 교환하기

s = [1,2,3,4,5]
s[0],s[-1] = s[-1],s[0]
print(s)

# 슬라이싱
s[0:2]

s = [1,2,3,4,5]
s[0:1] = [2,3]
print(s)
s[:2] = [10,20]
print(s)

s = [1,2,3,4,5,6,7]
s[0:7:2]

s[::2]

s1 = "Hello"
s2 = "World"
print(s1+s2)

s1*2

s1[0]

s1[0:2]

# 리스트와 달리 문자열은 내용을 바꿀수 없음
s1[0] = "K"

s1 = "Kello"
print(s1)

len([1,2,3])

def func1():
  t = [1,2,3]
  return t

l = func1()
print(l)

def func2(t):
  t = t + [4,5]
  return t

l = func2([1,2,3])
print(l)